### ISSUE TITLE
用了半天发现是解锁适配机型的哈哈哈

### ISSUE THREAD

**Issue by chizixiansheng** [zhang0281/UnlockMiui#1]
大佬能开发个解锁适配miui12.5的么，实在申请不到公测资格

**Comment by zhang0281** [comment]
现在这个模块的需求是这样的。
1. MIUI版本是12.5.
2. Android版本是 11.
3. 安装了提供的蓝奏云链接中的相关文件.
![图片](https://user-images.githubusercontent.com/34988981/111893753-ca81a980-8a3f-11eb-8d0a-8ab714f11619.png)
（没明白解锁适配miui12.5是什么意思。）

**Comment by zhang0281** [comment]
@chizixiansheng
