### ISSUE TITLE
红米note8pro失效

### ISSUE THREAD

**Issue by louha** [zhang0281/UnlockMiui#2]
红米note8pro 系统miui12.5，miui+解锁1.0.2 ，扫码后，电脑弹出连接界面之后，秒退出，无法连接。

**Comment by louha** [comment]
排查后发现是投屏功能无法使用，只要点开这个投屏，立马闪退。
![image](https://user-images.githubusercontent.com/17264572/126045259-ea3bdb62-078d-429c-8d8b-9f133973c2e6.png)

**Comment by zhang0281** [comment]
试一下使用核心破解后安装【小米互联通信服务，扫一扫，MIUI+ Beta版】。然后看看能不能恢复？
还是不能用的话请提供一下miui+和小米互联通信服务的安装包。我这边排查一下。

**Comment by louha** [comment]
已经核心破解了，解锁miui+是1.0.2的，系统是12.5开发版。miui+和小米互联通信服务使用的是模块仓库中蓝奏云链接里的版本https://wws.lanzoux.com/b01u1if2d密码h61h。并且更新最新版后也无效。不使用投屏功能时可以连接上，一旦点了投屏之后直接断开连接，同机型的其他用户也是这个情况。

**Comment by louha** [comment]
已经核心破解了，解锁miui+是1.0.2的，系统是12.5开发版。miui+和小米互联通信服务使用的是模块仓库中蓝奏云链接里的版本https://wws.lanzoux.com/b01u1if2d  密码h61h。并且更新最新版后也无效。不使用投屏功能时可以连接上，一旦点了投屏之后直接断开连接，同机型的其他用户也是这个情况。

**Comment by louha** [comment]
> 试一下使用核心破解后安装【小米互联通信服务，扫一扫，MIUI+ Beta版】。然后看看能不能恢复？
> 还是不能用的话请提供一下miui+和小米互联通信服务的安装包。我这边排查一下。

😭

**Comment by zhang0281** [comment]
那有可能是真的不支持了……

**Comment by modcrafts** [comment]
同样的问题
