### ISSUE TITLE
作者你好，能写一下模块具体工作原理嘛？

### ISSUE THREAD

**Issue by CharlesGool** [zhang0281/UnlockMiui#6]
想要让自己的Miui12 Android10也支持Miui+！目前Miui+的apk等安装上了，也转成系统App了，扫一扫直接跳转网页，可能是扫一扫判断我的系统版本过低之类的吧hhh，因为平时使用会去除root，更就没办法使用lsposed/xp之类的了，所以希望作者可以赐教，希望可以通过反编译App来实现这个功能，感谢！

**Comment by zhang0281** [comment]
1. 修改MIUI+

这个模块在制作的时候，MIUI+是有混淆的，2.1.0的版本是hook了com.xiaomi.mirror.ak这个类下的

![image](https://user-images.githubusercontent.com/34988981/155067623-e7724d7e-9661-4baa-a055-4ff4bfd112c0.png)

这个方法，这个就是用来检查手机型号是否支持MIUI+的。

而在新版本中，似乎是去掉了混淆，我提取的3.6.13版本的MIUI+是没有混淆的，于是需要hook的类就是com.xiaomi.mirror.utils.SystemUtils，只需要Hook这个方法(或者直接反编译修改这个方法)的返回值始终为True就可以了。

![jadx-gui](https://user-images.githubusercontent.com/34988981/155067251-469444b5-3fac-4f60-b171-fd7758d9c1f2.png)

2. 修改设置(com.android.settings)

因为MIUI+的入口在设置应用中是单独做的判断，所以如果想要显示入口还需要对设置做处理。具体可以参考[这个](https://github.com/zhang0281/UnlockMiui/blob/master/app/src/main/java/com/test/unlockmiui/AddMirrorSettingItem.java)

是将com.android.settings.connection.MiMirrorController这个类下的isMirrorSupported方法的返回值修改为固定返回True。


另外，也不排除随着版本更新，检测相关的代码变多的可能性……

这个模块停更的原因也是我手头的机型支持了MIUI+，而我这边没有其他机型用于测试。
