### ISSUE TITLE
MIUI+连接成功后，输入文字时就无法调用出键盘进行输入

### ISSUE THREAD

**Issue by jiebozhang** [zhang0281/UnlockMiui#8]
小米10S+MIUI12.5.1，设置→连接与共享下不显示MIUI+
但是安装UnlockMiui后，可以与PC MIUI+连接成功使用

现在bug是，连接成功后，输入文字时就无法调用出键盘进行输入

卸载UnlockMiui，重启输入文字，就可以正常调用键盘进行输入了

**Comment by zhang0281** [comment]
小米10S应该是已经获得了官方支持的，更新系统到新版本就可以使用 设备互联(MIUI+) 了。
无法调用键盘可能是旧版本MIUI+的bug，我之前遇到过。解决方式是锁屏再解锁屏幕就恢复正常了。
@jiebozhang
